# Generated by Django 4.1.3 on 2022-12-03 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="author",
        ),
    ]
