# Generated by Django 3.2.12 on 2022-12-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informs',
            name='content',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
