# Generated by Django 3.2.12 on 2022-12-09 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='noti_project', to='projects.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noti_todo', to='projects.todo'),
        ),
    ]
