# Generated by Django 3.2.12 on 2022-12-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='end_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='start_at',
            field=models.DateField(),
        ),
    ]
