# Generated by Django 3.2.12 on 2022-12-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20221207_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_at',
            field=models.DateField(),
        ),
    ]
