# Generated by Django 4.1.3 on 2022-11-29 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_skill_alter_project_user_todo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="todo_project",
                to="projects.project",
            ),
        ),
    ]
