# Generated by Django 4.1.3 on 2022-12-01 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_remove_project_leader_remove_project_members_members"),
    ]

    operations = [
        migrations.RenameField(
            model_name="members",
            old_name="post",
            new_name="project",
        ),
    ]
