# Generated by Django 4.1.3 on 2022-12-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_end_at_alter_project_start_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="members",
            name="user",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
