# Generated by Django 4.1.3 on 2022-11-29 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0003_alter_todo_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="members",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="project",
            name="user",
        ),
        migrations.AddField(
            model_name="project",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_user",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
