# Generated by Django 4.1.3 on 2022-12-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_rename_post_members_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="members",
            name="user",
            field=models.CharField(max_length=100),
        ),
    ]
