# Generated by Django 4.1.3 on 2022-12-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_members_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="members",
            name="user",
            field=models.CharField(max_length=100),
        ),
    ]
