# Generated by Django 4.1.3 on 2022-12-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_members_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="color",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
