# Generated by Django 4.1.3 on 2022-12-01 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_members_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="members",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
            ),
        ),
    ]
