# Generated by Django 4.1.3 on 2022-12-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_project_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="color",
            field=models.IntegerField(default=0),
        ),
    ]
