# Generated by Django 4.1.3 on 2022-12-02 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_project_author_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="user",
        ),
    ]
