# Generated by Django 4.1.3 on 2022-12-02 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_alter_comment_project"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="project",
            new_name="todo",
        ),
    ]
