# Generated by Django 3.2.12 on 2022-12-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification',
            field=models.ManyToManyField(related_name='notification_user', to='projects.Notification'),
        ),
    ]
