# Generated by Django 3.2.12 on 2022-12-08 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notification',
        ),
    ]
